### PR TITLE
Connect all pads of the same number in a footprint to the matching net 

### PR DESCRIPTION
**Pull request by snhobbs**
Added iterator to connect all pads of the same number to a given net. This mimics the behaviour of the GUI editor. Otherwise parts like via stitched mounting holes only have a single pad connected (such as one of several vias).

### CODE REVIEW

**Comment by devbisme** [comment]
The old API doesn't appear to have any way to handle multiple pads per pin number. So I just placed your multi-pad logic under the section of code that applies to the new API and left the old API stuff as-is. It's in my branch labeled "hobbs". Try it out on your test case and see if it works or if there are other changes that need to be made.

**Comment by snhobbs** [comment]
Works great!

## Previous Version
disconnected-pads

## Current Version
connected-pads

Thanks!

**Comment by devbisme** [comment]
We did it!

Thanks for showing an example. I had never seen this.

**Comment by adamws** [comment]
Encountered same problem, this is my fix on fork I'm using in my project: https://github.com/devbisme/kinet2pcb/commit/1fc8a4b67e9fbb25beade950c80d3cdc8d868c23
`for p in module.Pads():` works for KiCad 6 & 7

**Pull request merged**
